### ISSUE TITLE
Essentials nick names do not work with CM.

### ISSUE THREAD

**Issue by ghost** [PEXPlugins/ChatManager#17]
Nicknames show up on /list, and any other plugins that deals with names and chat.

however they dont work with ChatManager in chat.

PEX latest as of today
Bukkit 1.2.5 RB
Chat manager - PEX
Essentials latest DEV as of today.

**Comment by bacon-avenger** [comment]
Sure it does.  Change your chatmanager config to use the %displayname variable, which is what essentials uses.

PEX 1.19.1

**Comment by ghost** [comment]
Ill test this asap thank you. Is this on the wiki somewhere that I just
missed?
On Apr 6, 2012 1:43 AM, "Bacon Avenger" <
reply@reply.github.com>
wrote:

**Comment by bacon-avenger** [comment]
Not yet.  :)  I'll have to add to the chatmanager section that the environment variables in there are not set in stone.

If it does work out for you, please don't forget to close this ticket.
