### ISSUE TITLE
Factions in Prefix

### ISSUE THREAD

**Issue by TehDeathRider** [PEXPlugins/ChatManager#20]
I recently got factions on my server and it took a bad turn with my chat formatting. If you've got a faction it won't let you talk, I think it's because the faction name isn't included in the message format. How can I fix it? 

My Chat Manager config: 

" enable: true
message-format: '%displayname &8: &6%message'
global-message-format: '%displayname : &6%message'
ranged-mode: false
chat-range: 100.0 "

**Comment by LordRalex** [comment]
Can you give more information to this?

**Comment by zml2008** [comment]
ChatManager is no longer maintained - I'd suggest using [iChat](http://dev.bukkit.org/server-mods/ichat/) or another chat plugin instead.
