### ISSUE TITLE
Weird prefixes|suffixes when ranged-mode enabled

### ISSUE THREAD

**Issue by riffbyte** [PEXPlugins/ChatManager#21]
I am using only ChatManager to handle the chat and all prefixes and suffixes are set in group permissions.
When ranged mode was disabled, everything worked great.
But then I tried the ranged mode, and it works, but plugin doesn't seem to parse prefixes and suffixes.
More than that some players have strange prefix|suffix, that aren't set anywhere, like so:

&e[????]Sato: &6message

When without ranged-mode it normally looks like so:

[&6Admin&f] &bSato: &emessage

my ChatManager config.yml:

enable: true
message-format: '%prefix%player&f: %suffix%message'
global-message-format: '[&aG&f] %prefix%player&f: %suffix%message'
ranged-mode: true
chat-range: 150.0

PEX 1.19.2
CB 1.2.5-R1.3

**Comment by zml2008** [comment]
ChatManager is no longer maintained - I'd suggest using [iChat](http://dev.bukkit.org/server-mods/ichat/) instead.
