### ISSUE TITLE
ChatManager doesn't work in Bukkit 1.3.1-R0.1#2269

### ISSUE THREAD

**Issue by buschtoens** [PEXPlugins/ChatManager#24]
Neither with or without PermissionsEx.
`/pl` shows that it's loaded but is displayed in red.

**Comment by bacon-avenger** [comment]
It's working fine for me with Bukkit 1.3.1-R1.1#2326

**Comment by dionrhys** [comment]
That means it didn't enable on startup. Can you find any messages about ChatManager not enabling on starting up the server? Have you ensured it's enabled in ChatManager\config.yml?

**Comment by jaggy80** [comment]
ChatManager doesn't work for me using the Factions plugin that was recently updated for 1.3.  Remove Factions or downgrade Factions, then ChatManager will work again.  Not sure if this is a problem with Factions or ChatManager...  I'm guessing ChatManager needs updated to 1.3, but it could still be Factions...  I'm temporarily using EssentialsChat until theres a fix.  Hope this helps someone :o
