### ISSUE TITLE
Use AsyncPlayerChatEvent!

### ISSUE THREAD

**Issue by Psithief** [PEXPlugins/ChatManager#26]
http://jd.bukkit.org/apidocs/org/bukkit/event/player/AsyncPlayerChatEvent.html

ChatManager is forcing chat processing on the main thread, and this causes servers to LOCK UP when another plugin uses the  new **proper and intended** `v1.3.1` asynchronous chat.

This is a major compatibility issue, and it's **MOD EDIT: not** easy to fix too.

**Comment by zml2008** [comment]
It's not easy to fix. We need to make all of ChatManager thread-safe to use the async event.

**Comment by Psithief** [comment]
@zml2008 Yes, in _theory_ it's not easy. However, when it's zml2008 saying this I am incredulous - how many times have you already made plugins thread safe for chat purposes already? It's not zero. For you it should be (relatively) easy by now.

**Comment by zml2008** [comment]
I've updated plugins that have chat as a small component apart from their main function which accesses very little Bukkit API. ChatManager on the other hand is entirely a chat plugin, so every part of it has to be made thread-safe. It's also not my plugin.

**Comment by zml2008** [comment]
ChatManager is no longer maintained - closing.
