### ISSUE TITLE
Local listen for moderator

### ISSUE THREAD

**Issue by linkinkov** [PEXPlugins/ChatManager#27]
Hello its no bug, but very need permission in plugin that give for moderator listen local chat everywere.

Привет, это не баг, но очень нужно разрешение в плагин, которое дает модераторам слушать локальный чат везде.
Спасибо за плагин!

**Comment by t3hk0d3** [comment]
What do you mean "local chat"? Ranged mode? Than there is already such permission:

<code>chatmanager.override.ranged</code>

**Comment by linkinkov** [comment]
Its for say, not for listen.

**Comment by ItsTrigger** [comment]
Late response, but I think they're asking for a permission so that server staff can hear all ranged mode chat despite not being within range of those chatting.

**Comment by zml2008** [comment]
ChatManager is no longer maintained - I'd suggest using [iChat](http://dev.bukkit.org/server-mods/ichat/) instead.
