### ISSUE TITLE
Event priority

### ISSUE THREAD

**Issue by z2s8** [PEXPlugins/ChatManager#29]
Please specify event priorities to your listeners, because other plugins, (such as chat logger) can't pass the modified chat colours and others. I think chat color and prefix priorities should be "HIGHEST". Thanks

**Comment by zml2008** [comment]
The priority is currently NORMAL. Chat loggers should use HIGHEST or MONITOR for their event listeners.

**Comment by z2s8** [comment]
Oh, sorry then, I may misunderstood the source or not up to date.
