### ISSUE TITLE
%group placeholder

### ISSUE THREAD

**Issue by nickperkins** [PEXPlugins/ChatManager#3]
It would be useful to have a %group placeholder. This would allow a similar format to that currently used with iChat so that only the colour is held in %prefix. This then allows coloured names in plugins like MCDocs.

Cheers,
Nick

**Comment by m-rd-r** [comment]
I would love that

**Comment by zml2008** [comment]
ChatManager is no longer maintained - I'd suggest using [iChat](http://dev.bukkit.org/server-mods/ichat/) or another chat plugin instead.
