### ISSUE TITLE
chatmanager.chat.color.CODE

### ISSUE THREAD

**Issue by ghost** [PEXPlugins/ChatManager#7]
like in SignColours http://dev.bukkit.org/server-mods/signcolours/ a permission to use a specific color would be nice ;]

```
    signColours.e - Allow user to use the colour yellow (e)
    signColours.* - Allow user to use all colours 
```

**Comment by zml2008** [comment]
ChatManager is no longer maintained - I'd suggest using [iChat](http://dev.bukkit.org/server-mods/ichat/) or another chat plugin instead.
