### ISSUE TITLE
Player Prefix - Group Prefix

### ISSUE THREAD

**Issue by ghost** [PEXPlugins/ChatManager#9]
Hello. I would like more options in the config.

for example %pp where it puts the players prefix and then %gp where it puts the group prefix.

Then i can have everything in the group prefix displayed before anything in the player prefix or the other way around etc. Im not sure how it works now.

I tried setting a player prefix, and it overrode what was in the group prefix

**Comment by somasis** [comment]
Is there any progress on this at all?

**Comment by zml2008** [comment]
ChatManager is no longer maintained - I'd suggest using [iChat](http://dev.bukkit.org/server-mods/ichat/) instead.
